baseURL = 'https://youcandoithealth.com/'
languageCode = 'en-us'
title = 'You Can Do It Health Coaching'
theme = 'ananke'

[params]
  custom_css = ["css/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    name = "Meet Your Coach"
    url = "/meet-your-coach/"
    weight = 1
    
  [[menu.main]]
    name = "Newsletter"
    url = "https://eepurl.com/YOUR-MAILCHIMP-URL"
    weight = 2
    
  [[menu.main]]
    name = "Free Discovery Call"
    url = "/book-now/"
    weight = 3
