baseURL = 'https://youcandoithealth.com/'
languageCode = 'en-us'
title = 'You Can Do It Health Coaching'
theme = 'ananke'

[params]
  custom_css = ["css/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    name = "Meet Your Coach"
    url = "/meet-your-coach/"
    weight = 1
    
  [[menu.main]]
    name = "Newsletter"
    url = "https://eepurl.com/YOUR-MAILCHIMP-URL"
    weight = 2
    
  [[menu.main]]
    name = "Free Discovery Call"
    url = "/book-now/"
    weight = 3

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
    weight = 1
    
  [[menu.footer]]
    name = "Disclaimer"
    url = "/disclaimer/"
    weight = 2
    
  [[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 3
    
  [[menu.footer]]
    name = "Instagram"
    url = "http://instagram.com/youcandoithealth"
    weight = 4
    
  [[menu.footer]]
    name = "Facebook"
    url = "https://www.facebook.com/profile.php?id=61583343905186"
    weight = 5
    
  [[menu.footer]]
    name = "TikTok"
    url = "http://tiktok.com/@youcandoithealth"
    weight = 6
    
  [[menu.footer]]
    name = "YouTube"
    url = "https://www.youtube.com/@youcandoithealth"
    weight = 7
